version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:11.13.0-browsers
    steps:
      - checkout
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn test
# No real need for workflows yet but here for future use
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
