version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:12.3.1-browsers
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run: yarn test
      - run: yarn cypress:ci
# No real need for workflows yet but here for future use
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
