version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:11.14.0-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn cypress:run
# No real need for workflows yet but here for future use
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
