version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-browsers
    steps:
      - checkout
      - yarn -v
      - node -v
      - pwd
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
